name: Lint Pull Request Title
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  print_title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: lint commit
        run: echo '${{ github.event.pull_request.title }}' | npx commitlint
